version: "3.11"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"

  app:
    container_name: app
    image: app-image
    build:
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
